workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

stages:
  - test
  - build

run_unit_tests:
  image: node:17-alpine3.14
  stage: test
  tags:
  - docker
  - remote
  before_script:
  - cd app
  - npm i
  script:
  - npm test
  artifacts:
    when: always
    reports:
      junit: app/junit.xml

build_image:
  stage: build
  tags:
  - shell
  - remote
  script:
  - docker build -t registry.gitlab.com/un4ckn0wl3z/mynodeapp-cicd-project:1.0 .

push_image:
  stage: build
  needs:
  - build_image
  tags:
  - shell
  - remote
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script:
  - docker push registry.gitlab.com/un4ckn0wl3z/mynodeapp-cicd-project:1.0