workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

run_unit_tests:
  image: node:17-alpine3.14
  tags:
  - docker
  - remote
  before_script:
  - cd app
  - npm i
  script:
  - npm test
  artifacts:
    when: always
    reports:
      junit: app/junit.xml