image: node:17-alpine

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: never
    - when: always

stages:
  - test
  - build
  - deploy

variables:
  image_repository: docker.io/un4ckn0wl3z/myapp
  image_tag: v1.0

run_unit_tests:
  stage: test
  before_script:
    - echo "Preparing test data..."
  script:
    - echo "Running unit tests for microservice $MICRO_SERVICE_NAME ..."
    - npm version
  after_script:
    - echo "Cleaning up temporory files..."

run_lint_tests:
  stage: test
  before_script:
    - echo "Preparing test data..."
  script:
    - echo "Running lint tests..."
  after_script:
    - echo "Cleaning up temporory files..."

build_image:
  only:
    - master
  stage: build
  script:
    - echo "Building docker image..."
    - echo "Tagging the docker image $image_repository:$image_tag"

push_iamge:
  only:
    - master
  stage: build
  needs:
    - build_image
  script:
  - echo "Logging into docker registry"
  - echo "Pushing docker image $image_repository:$image_tag to registry..."

deploy_image:
  only:
    - master
  stage: deploy
  script:
  - echo "Deploying new docker image $image_repository:$image_tag to $DEPLOYMENT_ENVIRONMENT using the following configuation file - $PROPERTIES_FILE ..."
  - cat $PROPERTIES_FILE
  

