workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "master"
      when: never
    - when: always

stages:
  - test
  - build
  - deploy

run_unit_tests:
  stage: test
  before_script:
    - echo "Preparing test data..."
  script:
    - echo "Running unit tests..."
  after_script:
    - echo "Cleaning up temporory files..."

run_lint_tests:
  stage: test
  before_script:
    - echo "Preparing test data..."
  script:
    - echo "Running lint tests..."
  after_script:
    - echo "Cleaning up temporory files..."

build_image:
  stage: build
  script:
    - echo "Building docker image..."
    - echo "Tagging the docker iamge"

push_iamge:
  stage: build
  needs:
    - build_image
  script:
  - echo "Logging into docker registry"
  - echo "Pushing docker iamge to registry..."

deploy_image:
  stage: deploy
  script:
  - echo "Deploying new docker image to DEV server..."
  

