run_tests:
  before_script:
    - echo "Preparing test data..."
  script:
    - echo "Running tests..."
  after_script:
    - echo "Cleaning up temporory files..."

build_image:
  script:
    - echo "Building docker image..."
    - echo "Tagging the docker iamge"

push_iamge:
  script:
  - echo "Logging into docker registry"
  - echo "Pushing docker iamge to registry..."
